name: Odie is Epic
favicon: null
layout_spectrum: 0.6641991601791233
typography_spectrum: 0.45287289726547897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3495168664958328
  lightness: 0.6558171131182462
  saturation: 0.3052829806692898
  rhythmicContrast: 0.42556991265155375
purpose: []
