name: Odie is Epic
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12016
title: Odie is Epic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090a05'
    - '#357f80'
    - '#34373e'
    - '#f1cd1f'
    - '#cb8103'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
